php_exam/Store/src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InvoiceRepository::class)]
class Invoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $transaction_date = null;

    #[ORM\Column]
    private ?float $billing_total = null;

    #[ORM\Column(length: 50)]
    private ?string $billing_adress = null;

    #[ORM\Column(length: 30)]
    private ?string $billing_city = null;

    #[ORM\Column]
    private ?int $billing_zip_code = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getTransactionDate(): ?\DateTimeInterface
    {
        return $this->transaction_date;
    }

    public function setTransactionDate(\DateTimeInterface $transaction_date): static
    {
        $this->transaction_date = $transaction_date;

        return $this;
    }

    public function getBillingTotal(): ?float
    {
        return $this->billing_total;
    }

    public function setBillingTotal(float $billing_total): static
    {
        $this->billing_total = $billing_total;

        return $this;
    }

    public function getBillingAdress(): ?string
    {
        return $this->billing_adress;
    }

    public function setBillingAdress(string $billing_adress): static
    {
        $this->billing_adress = $billing_adress;

        return $this;
    }

    public function getBillingCity(): ?string
    {
        return $this->billing_city;
    }

    public function setBillingCity(string $billing_city): static
    {
        $this->billing_city = $billing_city;

        return $this;
    }

    public function getBillingZipCode(): ?int
    {
        return $this->billing_zip_code;
    }

    public function setBillingZipCode(int $billing_zip_code): static
    {
        $this->billing_zip_code = $billing_zip_code;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

php_exam/Store/src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Invoice;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('user_id')
            ->add('transaction_date')
            ->add('billing_total')
            ->add('billing_adress')
            ->add('billing_city')
            ->add('billing_zip_code')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

php_exam/Store/src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/invoice')]
class InvoiceController extends AbstractController
{
    #[Route('/', name: 'app_invoice_index', methods: ['GET'])]
    public function index(InvoiceRepository $invoiceRepository): Response
    {
        return $this->render('invoice/index.html.twig', [
            'invoices' => $invoiceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_invoice_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($invoice);
            $entityManager->flush();

            return $this->redirectToRoute('app_invoice_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_invoice_show', methods: ['GET'])]
    public function show(Invoice $invoice): Response
    {
        return $this->render('invoice/show.html.twig', [
            'invoice' => $invoice,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_invoice_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Invoice $invoice, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_invoice_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_invoice_delete', methods: ['POST'])]
    public function delete(Request $request, Invoice $invoice, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$invoice->getId(), $request->request->get('_token'))) {
            $entityManager->remove($invoice);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_invoice_index', [], Response::HTTP_SEE_OTHER);
    }
}

php_exam/Store/templates/invoice/_delete_form.html.twig
<form method="post" action="{{ path('app_invoice_delete', {'id': invoice.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn">Delete</button>
</form>

php_exam/Store/templates/invoice/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

php_exam/Store/templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Invoice{% endblock %}

{% block body %}
    <h1>Edit Invoice</h1>

    {{ include('invoice/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_invoice_index') }}">back to list</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}

php_exam/Store/templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice index{% endblock %}

{% block body %}
    <h1>Invoice index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User_id</th>
                <th>Transaction_date</th>
                <th>Billing_total</th>
                <th>Billing_adress</th>
                <th>Billing_city</th>
                <th>Billing_zip_code</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
            <tr>
                <td>{{ invoice.id }}</td>
                <td>{{ invoice.userId }}</td>
                <td>{{ invoice.transactionDate ? invoice.transactionDate|date('Y-m-d') : '' }}</td>
                <td>{{ invoice.billingTotal }}</td>
                <td>{{ invoice.billingAdress }}</td>
                <td>{{ invoice.billingCity }}</td>
                <td>{{ invoice.billingZipCode }}</td>
                <td>
                    <a href="{{ path('app_invoice_show', {'id': invoice.id}) }}">show</a>
                    <a href="{{ path('app_invoice_edit', {'id': invoice.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_invoice_new') }}">Create new</a>
{% endblock %}

php_exam/Store/templates/invoice/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Invoice{% endblock %}

{% block body %}
    <h1>Create new Invoice</h1>

    {{ include('invoice/_form.html.twig') }}

    <a href="{{ path('app_invoice_index') }}">back to list</a>
{% endblock %}

php_exam/Store/templates/invoice/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice{% endblock %}

{% block body %}
    <h1>Invoice</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ invoice.id }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ invoice.userId }}</td>
            </tr>
            <tr>
                <th>Transaction_date</th>
                <td>{{ invoice.transactionDate ? invoice.transactionDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Billing_total</th>
                <td>{{ invoice.billingTotal }}</td>
            </tr>
            <tr>
                <th>Billing_adress</th>
                <td>{{ invoice.billingAdress }}</td>
            </tr>
            <tr>
                <th>Billing_city</th>
                <td>{{ invoice.billingCity }}</td>
            </tr>
            <tr>
                <th>Billing_zip_code</th>
                <td>{{ invoice.billingZipCode }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_invoice_index') }}">back to list</a>

    <a href="{{ path('app_invoice_edit', {'id': invoice.id}) }}">edit</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}