php_exam/Store/src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $article_name = null;

    #[ORM\Column(length: 255)]
    private ?string $article_description = null;

    #[ORM\Column]
    private ?float $article_price = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column]
    private ?int $author_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $article_pic = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticleName(): ?string
    {
        return $this->article_name;
    }

    public function setArticleName(string $article_name): static
    {
        $this->article_name = $article_name;

        return $this;
    }

    public function getArticleDescription(): ?string
    {
        return $this->article_description;
    }

    public function setArticleDescription(string $article_description): static
    {
        $this->article_description = $article_description;

        return $this;
    }

    public function getArticlePrice(): ?float
    {
        return $this->article_price;
    }

    public function setArticlePrice(float $article_price): static
    {
        $this->article_price = $article_price;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->author_id;
    }

    public function setAuthorId(int $author_id): static
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getArticlePic(): ?string
    {
        return $this->article_pic;
    }

    public function setArticlePic(?string $article_pic): static
    {
        $this->article_pic = $article_pic;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

php_exam/Store/src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\Articles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('article_name')
            ->add('article_description')
            ->add('article_price')
            ->add('publication_date')
            ->add('author_id')
            ->add('article_pic')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

php_exam/Store/src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/articles')]
class ArticlesController extends AbstractController
{
    #[Route('/', name: 'app_articles_index', methods: ['GET'])]
    public function index(ArticlesRepository $articlesRepository): Response
    {
        return $this->render('articles/index.html.twig', [
            'articles' => $articlesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_articles_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Articles();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('articles/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_articles_show', methods: ['GET'])]
    public function show(Articles $article): Response
    {
        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_articles_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Articles $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('articles/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_articles_delete', methods: ['POST'])]
    public function delete(Request $request, Articles $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
    }
}

php_exam/Store/templates/articles/_delete_form.html.twig
<form method="post" action="{{ path('app_articles_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

php_exam/Store/templates/articles/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

php_exam/Store/templates/articles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Articles{% endblock %}

{% block body %}
    <h1>Edit Articles</h1>

    {{ include('articles/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_articles_index') }}">back to list</a>

    {{ include('articles/_delete_form.html.twig') }}
{% endblock %}

php_exam/Store/templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles index{% endblock %}

{% block body %}
    <h1>Articles index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Article_name</th>
                <th>Article_description</th>
                <th>Article_price</th>
                <th>Publication_date</th>
                <th>Author_id</th>
                <th>Article_pic</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.articleName }}</td>
                <td>{{ article.articleDescription }}</td>
                <td>{{ article.articlePrice }}</td>
                <td>{{ article.publicationDate ? article.publicationDate|date('Y-m-d') : '' }}</td>
                <td>{{ article.authorId }}</td>
                <td>{{ article.articlePic }}</td>
                <td>
                    <a href="{{ path('app_articles_show', {'id': article.id}) }}">show</a>
                    <a href="{{ path('app_articles_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_articles_new') }}">Create new</a>
{% endblock %}

php_exam/Store/templates/articles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Articles{% endblock %}

{% block body %}
    <h1>Create new Articles</h1>

    {{ include('articles/_form.html.twig') }}

    <a href="{{ path('app_articles_index') }}">back to list</a>
{% endblock %}

php_exam/Store/templates/articles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
    <h1>Articles</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Article_name</th>
                <td>{{ article.articleName }}</td>
            </tr>
            <tr>
                <th>Article_description</th>
                <td>{{ article.articleDescription }}</td>
            </tr>
            <tr>
                <th>Article_price</th>
                <td>{{ article.articlePrice }}</td>
            </tr>
            <tr>
                <th>Publication_date</th>
                <td>{{ article.publicationDate ? article.publicationDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Author_id</th>
                <td>{{ article.authorId }}</td>
            </tr>
            <tr>
                <th>Article_pic</th>
                <td>{{ article.articlePic }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_articles_index') }}">back to list</a>

    <a href="{{ path('app_articles_edit', {'id': article.id}) }}">edit</a>

    {{ include('articles/_delete_form.html.twig') }}
{% endblock %}